-- B4ES Ledger: core double-entry schema.
--
-- Money is always INTEGER pence. Posted journals are immutable: corrections
-- are made by posting a reversal. The triggers below are the last line of
-- defence; the Worker runs the same checks first to give friendly errors.


-- ------------------------------------------------------------ entities
-- One row per set of books: B4ES LLP first, client companies later.
CREATE TABLE entities (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  name            TEXT    NOT NULL,
  legal_form      TEXT    NOT NULL DEFAULT 'llp'
                  CHECK (legal_form IN ('llp','ltd','sole_trader','partnership','charity','other')),
  company_number  TEXT,
  base_ccy        TEXT    NOT NULL DEFAULT 'GBP',
  fy_end_month    INTEGER NOT NULL DEFAULT 12 CHECK (fy_end_month BETWEEN 1 AND 12),
  fy_end_day      INTEGER NOT NULL DEFAULT 31 CHECK (fy_end_day BETWEEN 1 AND 31),
  vat_registered  INTEGER NOT NULL DEFAULT 0 CHECK (vat_registered IN (0,1)),
  notes           TEXT,
  status          TEXT    NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ---------------------------------------------------------- principals
-- People who have signed in through Cloudflare Access (and, later, agents).
CREATE TABLE principals (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  email         TEXT    NOT NULL UNIQUE COLLATE NOCASE,
  display_name  TEXT,
  role          TEXT    NOT NULL DEFAULT 'partner' CHECK (role IN ('admin','partner','viewer','agent')),
  active        INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_at    TEXT    NOT NULL DEFAULT (datetime('now')),
  last_seen_at  TEXT
);

-- ------------------------------------------------------------ accounts
CREATE TABLE accounts (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_id   INTEGER NOT NULL REFERENCES entities(id),
  code        TEXT    NOT NULL,
  name        TEXT    NOT NULL,
  type        TEXT    NOT NULL CHECK (type IN ('asset','liability','equity','income','expense')),
  subtype     TEXT,            -- e.g. fixed_asset, current_asset, cash, current_liability ...
  fs_line     TEXT,            -- statement line key, e.g. turnover, admin_expenses, debtors
  cf_class    TEXT             -- cash-flow class for balance sheet accounts
              CHECK (cf_class IS NULL OR cf_class IN ('cash','working_capital','non_cash','investing','financing')),
  is_bank     INTEGER NOT NULL DEFAULT 0 CHECK (is_bank IN (0,1)),
  active      INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE (entity_id, code)
);

-- -------------------------------------------------------- fiscal years
CREATE TABLE fiscal_years (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_id   INTEGER NOT NULL REFERENCES entities(id),
  start_date  TEXT    NOT NULL CHECK (start_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  end_date    TEXT    NOT NULL CHECK (end_date   GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  status      TEXT    NOT NULL DEFAULT 'open' CHECK (status IN ('open','locked')),
  locked_by   INTEGER REFERENCES principals(id),
  locked_at   TEXT,
  CHECK (end_date >= start_date),
  UNIQUE (entity_id, start_date)
);

-- ------------------------------------------------------------ contacts
CREATE TABLE contacts (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_id   INTEGER NOT NULL REFERENCES entities(id),
  name        TEXT    NOT NULL,
  kind        TEXT    NOT NULL DEFAULT 'other' CHECK (kind IN ('customer','supplier','member','employee','other')),
  active      INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  UNIQUE (entity_id, name)
);

-- ------------------------------------------------------------ journals
-- status: draft -> (pending ->) posted, or pending -> rejected.
CREATE TABLE journals (
  id               TEXT    PRIMARY KEY,                 -- ULID generated by the Worker
  entity_id        INTEGER NOT NULL REFERENCES entities(id),
  number           INTEGER,                             -- assigned only when posted
  date             TEXT    NOT NULL CHECK (date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  reference        TEXT,
  narrative        TEXT    NOT NULL,
  status           TEXT    NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending','posted','rejected')),
  source           TEXT    NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','quick','claude','reversal','opening','import')),
  requires_second  INTEGER NOT NULL DEFAULT 0 CHECK (requires_second IN (0,1)),
  requested_approver_id INTEGER REFERENCES principals(id),
  total_p          INTEGER NOT NULL DEFAULT 0 CHECK (total_p >= 0),
  created_by       INTEGER NOT NULL REFERENCES principals(id),
  created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  submitted_at     TEXT,
  decided_by       INTEGER REFERENCES principals(id),
  decided_at       TEXT,
  decision_note    TEXT,
  posted_by        INTEGER REFERENCES principals(id),
  posted_at        TEXT,
  reversal_of      TEXT    REFERENCES journals(id),
  reversed_by      TEXT    REFERENCES journals(id),
  UNIQUE (entity_id, number)
);

CREATE INDEX idx_journals_entity_date   ON journals(entity_id, date);
CREATE INDEX idx_journals_entity_status ON journals(entity_id, status);

CREATE TABLE journal_lines (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  journal_id   TEXT    NOT NULL REFERENCES journals(id),
  line_no      INTEGER NOT NULL,
  account_id   INTEGER NOT NULL REFERENCES accounts(id),
  contact_id   INTEGER REFERENCES contacts(id),
  description  TEXT,
  debit_p      INTEGER NOT NULL DEFAULT 0 CHECK (debit_p  >= 0 AND debit_p  = CAST(debit_p AS INTEGER)),
  credit_p     INTEGER NOT NULL DEFAULT 0 CHECK (credit_p >= 0 AND credit_p = CAST(credit_p AS INTEGER)),
  vat_code     TEXT,
  CHECK ((debit_p > 0) <> (credit_p > 0)),
  UNIQUE (journal_id, line_no)
);

CREATE INDEX idx_lines_account ON journal_lines(account_id);
CREATE INDEX idx_lines_journal ON journal_lines(journal_id);

-- ----------------------------------------------------------- audit log
CREATE TABLE audit_log (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  at            TEXT    NOT NULL DEFAULT (datetime('now')),
  principal_id  INTEGER REFERENCES principals(id),
  action        TEXT    NOT NULL,
  entity_id     INTEGER,
  object_type   TEXT,
  object_id     TEXT,
  detail_json   TEXT
);

CREATE INDEX idx_audit_entity ON audit_log(entity_id, at DESC);

-- ============================================================ triggers

-- A journal can never be created already posted: it must be inserted as a
-- draft or pending and then posted, so the posting checks below always run.
CREATE TRIGGER trg_journals_no_insert_posted
BEFORE INSERT ON journals
WHEN NEW.status = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: journals must be posted from draft or pending');
END;

-- Posting checks: balanced, at least two lines, non-zero, number assigned,
-- accounts active and in the same entity, year not locked, and for entries
-- sent for second approval, approved by someone other than the creator.
CREATE TRIGGER trg_journals_post_checks
BEFORE UPDATE OF status ON journals
WHEN NEW.status = 'posted' AND OLD.status <> 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: a journal needs at least two lines')
   WHERE (SELECT COUNT(*) FROM journal_lines WHERE journal_id = NEW.id) < 2;
  SELECT RAISE(ABORT, 'ledger: debits and credits must be equal')
   WHERE (SELECT COALESCE(SUM(debit_p),0) - COALESCE(SUM(credit_p),0) FROM journal_lines WHERE journal_id = NEW.id) <> 0;
  SELECT RAISE(ABORT, 'ledger: a journal cannot total zero')
   WHERE (SELECT COALESCE(SUM(debit_p),0) FROM journal_lines WHERE journal_id = NEW.id) = 0;
  SELECT RAISE(ABORT, 'ledger: total_p must match the lines')
   WHERE NEW.total_p <> (SELECT COALESCE(SUM(debit_p),0) FROM journal_lines WHERE journal_id = NEW.id);
  SELECT RAISE(ABORT, 'ledger: a posted journal needs a number')
   WHERE NEW.number IS NULL;
  SELECT RAISE(ABORT, 'ledger: every account must be active and belong to this entity')
   WHERE EXISTS (SELECT 1 FROM journal_lines l JOIN accounts a ON a.id = l.account_id
                  WHERE l.journal_id = NEW.id AND (a.entity_id <> NEW.entity_id OR a.active = 0));
  SELECT RAISE(ABORT, 'ledger: that date is in a locked financial year')
   WHERE EXISTS (SELECT 1 FROM fiscal_years f
                  WHERE f.entity_id = NEW.entity_id AND f.status = 'locked'
                    AND NEW.date BETWEEN f.start_date AND f.end_date);
  SELECT RAISE(ABORT, 'ledger: a second approval must be by a different partner')
   WHERE OLD.status = 'pending' AND OLD.requires_second = 1
     AND (NEW.decided_by IS NULL OR NEW.decided_by = OLD.created_by);
  SELECT RAISE(ABORT, 'ledger: drafts sent for second approval cannot be posted directly')
   WHERE OLD.status = 'draft' AND OLD.requires_second = 1;
END;

-- Posted journals are immutable, except that reversed_by may be set once.
CREATE TRIGGER trg_journals_posted_immutable
BEFORE UPDATE ON journals
WHEN OLD.status = 'posted'
 AND NOT (
       NEW.status = 'posted'
   AND NEW.entity_id = OLD.entity_id
   AND NEW.number IS OLD.number
   AND NEW.date = OLD.date
   AND NEW.narrative IS OLD.narrative
   AND NEW.reference IS OLD.reference
   AND NEW.total_p = OLD.total_p
   AND NEW.posted_by IS OLD.posted_by
   AND NEW.posted_at IS OLD.posted_at
   AND NEW.reversal_of IS OLD.reversal_of
   AND OLD.reversed_by IS NULL AND NEW.reversed_by IS NOT NULL
 )
BEGIN
  SELECT RAISE(ABORT, 'ledger: posted journals cannot be changed; post a reversal instead');
END;

CREATE TRIGGER trg_journals_posted_no_delete
BEFORE DELETE ON journals
WHEN OLD.status = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: posted journals cannot be deleted');
END;

-- Lines of a posted journal cannot be added, changed or removed.
CREATE TRIGGER trg_lines_no_insert_posted
BEFORE INSERT ON journal_lines
WHEN (SELECT status FROM journals WHERE id = NEW.journal_id) = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: cannot add lines to a posted journal');
END;

CREATE TRIGGER trg_lines_no_update_posted
BEFORE UPDATE ON journal_lines
WHEN (SELECT status FROM journals WHERE id = OLD.journal_id) = 'posted'
  OR (SELECT status FROM journals WHERE id = NEW.journal_id) = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: cannot change lines of a posted journal');
END;

CREATE TRIGGER trg_lines_no_delete_posted
BEFORE DELETE ON journal_lines
WHEN (SELECT status FROM journals WHERE id = OLD.journal_id) = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: cannot remove lines of a posted journal');
END;

-- Accounts with posted history cannot be deleted or change type.
CREATE TRIGGER trg_accounts_no_delete_used
BEFORE DELETE ON accounts
WHEN EXISTS (SELECT 1 FROM journal_lines WHERE account_id = OLD.id)
BEGIN
  SELECT RAISE(ABORT, 'ledger: this account has entries; deactivate it instead');
END;

CREATE TRIGGER trg_accounts_no_retype_used
BEFORE UPDATE OF type, entity_id ON accounts
WHEN (NEW.type <> OLD.type OR NEW.entity_id <> OLD.entity_id)
 AND EXISTS (SELECT 1 FROM journal_lines l JOIN journals j ON j.id = l.journal_id
              WHERE l.account_id = OLD.id AND j.status = 'posted')
BEGIN
  SELECT RAISE(ABORT, 'ledger: cannot change the type of an account with posted entries');
END;

-- Unlocking a year is allowed (admins only, checked in the Worker) but
-- fiscal years with posted entries cannot be deleted.
CREATE TRIGGER trg_fy_no_delete_used
BEFORE DELETE ON fiscal_years
WHEN EXISTS (SELECT 1 FROM journals j WHERE j.entity_id = OLD.entity_id AND j.status = 'posted'
              AND j.date BETWEEN OLD.start_date AND OLD.end_date)
BEGIN
  SELECT RAISE(ABORT, 'ledger: this financial year has posted entries');
END;

-- Entities are never hard-deleted (record keeping); archive instead.
CREATE TRIGGER trg_entities_no_delete
BEFORE DELETE ON entities
BEGIN
  SELECT RAISE(ABORT, 'ledger: entities cannot be deleted; archive instead');
END;

-- The audit log is append-only.
CREATE TRIGGER trg_audit_no_update
BEFORE UPDATE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'ledger: the audit log cannot be changed');
END;

CREATE TRIGGER trg_audit_no_delete
BEFORE DELETE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'ledger: the audit log cannot be changed');
END;
