-- B4ES Ledger: supporting documents on entries (27 Sep 2026, Faisal).
-- The file itself lives in the R2 bucket b4es-ledger-documents (EU); this
-- table holds what it is, whose it is and a SHA-256 of its contents.
-- Documents can be added to any entry at any time; once the entry is posted
-- they can no longer be removed, and a document record is never changed.

CREATE TABLE documents (
  id            TEXT    PRIMARY KEY,                 -- ULID generated by the Worker
  entity_id     INTEGER NOT NULL REFERENCES entities(id),
  journal_id    TEXT    NOT NULL REFERENCES journals(id),
  filename      TEXT    NOT NULL CHECK (length(filename) BETWEEN 1 AND 200),
  content_type  TEXT    NOT NULL,
  size          INTEGER NOT NULL CHECK (size > 0 AND size <= 26214400),  -- 25 MB
  sha256        TEXT    NOT NULL CHECK (length(sha256) = 64),
  r2_key        TEXT    NOT NULL UNIQUE,
  note          TEXT,
  uploaded_by   INTEGER NOT NULL REFERENCES principals(id),
  uploaded_at   TEXT    NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_documents_journal ON documents (journal_id);

-- A document belongs to the same company as its entry.
CREATE TRIGGER trg_documents_same_entity
BEFORE INSERT ON documents
WHEN NEW.entity_id IS NOT (SELECT entity_id FROM journals WHERE id = NEW.journal_id)
BEGIN
  SELECT RAISE(ABORT, 'ledger: a document must belong to the same company as its entry');
END;

CREATE TRIGGER trg_documents_no_update
BEFORE UPDATE ON documents
BEGIN
  SELECT RAISE(ABORT, 'ledger: documents cannot be changed; remove and add again');
END;

CREATE TRIGGER trg_documents_no_delete_posted
BEFORE DELETE ON documents
WHEN (SELECT status FROM journals WHERE id = OLD.journal_id) = 'posted'
BEGIN
  SELECT RAISE(ABORT, 'ledger: documents on a posted entry cannot be removed');
END;
